image: docker

stages:
  - build
  - push

variables:
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  tags:
    - docker
  script:
    - docker image build -t $IMAGE .

push:
  stage: push
  tags:
    - docker
  only:
    - develop
    - master
  script:
    - docker image push $IMAGE
